### ISSUE TITLE
build-project command fails due to TOML decode error with Poetry 1.5.0 on Windows

### ISSUE THREAD

**Issue by nurbo** [DavidVujic/poetry-multiproject-plugin#30]
**Describe the bug**
I've been successfully running _poetry_ and the multiproject plugin with development version of _poetry_ (and with 1.4.2 before that). After updating to the newly released 1.5.0, there's a `TOMLDecodeError` exception thrown when reading the transient _pyproject.toml_ when building a project.

The exception is thrown at `lib\site-packages\tomli\_parser.py:127 in loads`, and is thrown because the compatibility TOML library, _tomli_ expects a newline character exactly, and doesn't handle the `\r\n` sequence. It seems to be an issue primarily with _tomli_, but could also be addressed by normalizing newlines when creating project files.

The relevant stack trace is:

```
   7  .poetry-venv\lib\site-packages\poetry_multiproject_plugin\commands\buildproject\project.py:88 in handle
        86│             self.rewrite_modules(project_path, top_ns)
        87│
     →  88│         self.prepare_for_build(project_path.absolute())
        89│
        90│         super(ProjectBuildCommand, self).handle()

   6  .poetry-venv\lib\site-packages\poetry_multiproject_plugin\commands\buildproject\project.py:73 in prepare_for_build
        71│
        72│     def prepare_for_build(self, path: Path):
     →  73│         project_poetry = Factory().create_poetry(path)
        74│
        75│         self.set_poetry(project_poetry)
```

The path comes from `create.create_new_project_file`.

I tried with Python versions 3.8.10 and 3.11.2 on Windows 10.

**To Reproduce**

1. Create a virtual environment
2. Install `poetry==1.5.0` and `poetry-multiproject-plugin` (optionally the `poety-polylith-plugin`),
3. Create a sample _poetry_ project
4. Create a project, for example with the _polylith_ tool, for example at _projects/test_,
5. Lock the project at _project/test_,
6. Run the command `poetry -vvv build-project -C project/test`, (or to debug run `python -m pdb -c continue -m poetry -vvv build-project -C project/test`,
6. Observe the error.

**Error Log**
The error should be roughly:

```
Loading the poetry-multiproject-plugin plugin
Loading the export plugin
Loading the poetry-polylith-plugin plugin
Using virtualenv: C:\Users\...\.poetry-venv
Using C:\Users\...\projects\test\pyproject.toml
Copied project & packages into temporary folder C:\Users\...\projects\.prepare_test
Generated C:\Users\...\projects\.prepare_test\pyproject.toml

TOMLDecodeError

  Expected newline or end of document after a statement (at line 1, column 14)

  at .poetry-venv\lib\site-packages\tomli\_parser.py:127 in loads
      123│             char = src[pos]
      124│         except IndexError:
      125│             break
      126│         if char != "\n":
    → 127│             raise suffixed_err(
      128│                 src, pos, "Expected newline or end of document after a statement"
      129│             )
      130│         pos += 1
      131│
````

On 3.11.2, with built-in `tomllib` the same error is thrown:

```
 at ...\3.11.2\Lib\tomllib\_parser.py:127 in loads
      123│             char = src[pos]
      124│         except IndexError:
      125│             break
      126│         if char != "\n":
    → 127│             raise suffixed_err(
      128│                 src, pos, "Expected newline or end of document after a statement"
      129│             )
      130│         pos += 1
```

**Expected behavior**
Loading the intermediate/transient project file during `build-project` should not fail due to TOML decoding errors.

The error does not appear when I insert the following line after _components/project/create.py:11_:

```diff
    generated = generate.generate_valid_dist_project_file(original, top_ns)
+   generated = generated.replace("\r\n", "\n")
```

**Desktop**
 - OS: Windows 10
 - Python version: 3.8.10 and 3.11.2
 - Poetry version: 1.5.0

**Comment by DavidVujic** [comment]
Thank you @nurbo for reporting this issue!

I will have a look at it. I didn't experience any issues when upgrading to Poetry 1.5 on Mac OS X, and suspect this error might be OS-specific. The change made seems to be replacing tomlkit with tomli according to the [changelog](https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md).

I will try to reproduce the error you experienced on Windows (and also Linux) and find a solution for it - your suggestion might be the best solution.

**Comment by DavidVujic** [comment]
I believe the error is fixed, and have released a new version of the poetry-multiproject-plugin: v1.2.2

The issue was about Windows vs *nix line endings and the solution I chose was to set the `newline` property of `open` to an empty string. If I understand the docs correctly it will leave line endings unchanged. 

https://docs.python.org/3/library/functions.html#open

Thank you again for reporting this and sharing a very detailed description with useful information! ⭐ 👏 

Please let me know if it has solved your issue, otherwise please reopen or create a new issue.
