### ISSUE TITLE
Make mypy an optional dependency or loosen the dep requirement 

### ISSUE THREAD

**Issue by nazq** [DavidVujic/poetry-multiproject-plugin#47]
**Is your feature request related to a problem? Please describe.**
I have a large set of repos I'm moving to the mono repo structure. We're currently on the latest mypy which gets downgraded with the plugin being in the base env. 

**Describe the solution you'd like**
I'm playing with creating a build venv for poetry but may run into issues with the CI/CD we use. Ideally we'd have mypy as optional and opt-in or allow the version to vary past 1.x. If it were optional I just wouldn't use the checker, we have a whole tox setup and pre-commit for this anyway

**Describe alternatives you've considered**
As above

**Additional context**
Many thanks for all the work here

**Comment by nazq** [comment]
I'm trying the poetry config system-site-packages = false, need to see if that has other unintended side effects

**Comment by nazq** [comment]
appreciate that. as an fyi the system-site-packages = false didn't quite work

**Comment by nazq** [comment]
> Thank you for reporting this @nazq!
> 
> This is a bug, and should be fixed. I'll look at it right away.

What are your thoughts on how to fix this ?

**Comment by DavidVujic** [comment]
Out of curiosity, how do you add the multiproject-plugin to Poetry? I think that I had thought of it as not disturbing the project specific dependencies, because it being installed in a Poetry-specific virtual environment.

**Comment by nazq** [comment]
let me try one more thing (might still not work for our CI/CD but worth a try). I'll do the following:-

- Clear proj .venv .tox envs
- Clear all base env packages
- Create a py-build env and only install poetry and the two plugins (plus my own)
- Then poetry install using poetry from the build-env in my proj to create the venv 

... should take a few mins

**Comment by nazq** [comment]
> Out of curiosity, how do you add the multiproject-plugin to Poetry? I think that I had thought of it as not disturbing the project specific dependencies, because it being installed in a Poetry-specific virtual environment.

We're not able to use the `poetry self add poetry-multiproject-plugin` style for poetry in a corp env as we use an internal pypi. So I have to pip install them

**Comment by DavidVujic** [comment]
That would explain it, thank you! MyPy is included because of the `check-project` command. But I think it should be fine for the multiproject plugin to allow any version (i.e. "*").

**Comment by nazq** [comment]
that would be perfect. I'll upgrade straight away

**Comment by nazq** [comment]
I see the new version. Many thanks, will give it a try

**Comment by DavidVujic** [comment]
@nazq 

A suggestion, would it be possible to install the plugin with pip but into the separate Poetry environment? Something like: 

``` shell
$POETRY_HOME/bin/pip install --user poetry-multiproject-plugin
```

https://python-poetry.org/docs/plugins/#with-pip

**Comment by nazq** [comment]
Looked at the new pkg and the PKG-INFO has this 

Requires-Dist: mypy (==1.*)
Requires-Dist: poetry (>=1.2,<2.0)
Requires-Dist: tomlkit (==0.*)

which should be fine. Only thing is that since mypy doesn't use semver I forget what their strategy is for a major release change

**Comment by nazq** [comment]
all seems to work fine now. Many thanks for the quick turnaround David
