### ISSUE TITLE
Multi-project doesn't respect third party dependencies for submodules 

### ISSUE THREAD

**Issue by peeksake** [DavidVujic/poetry-multiproject-plugin#59]
**Describe the bug**
I have the following tree.

Toplevel
| pyproject.toml
| App
&emsp;| - pyproject.toml
| Submodules .... 
&emsp;| - pyproject.toml
| Core
&emsp;| - pyproject.toml
  
The core pyproject toml is setup using poetry. 
```
[tool.poetry.dependencies]
requests = "^2.31"
```

Then the app pyproject toml 
Has the following sections
```
[tool.poetry]
name = "app"
packages = [
  { include = "core", from = "../core" },
]
[tool.poetry.dependencies]
python = ">=3.9.16, <3.13"
core = { path = "../core", develop = true }
```

**To Reproduce**
1. `poetry build-project`

**Error Log**
If applicable, add the error logs.
Metadata of the created poetry installer
```
Metadata-Version: 2.1
Name: app
Version: 0.1.0
Summary: 
Requires-Python: >=3.11,<4.0
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3.12
```

**Expected behavior**
Would expect to see all the nested deps in the `Requires-Dist` portion of the whl.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python version: 3.11 
 - Poetry version: 1.8.1

**Additional context**

**Comment by DavidVujic** [comment]
Thank you for reporting this!


The Multi-project plugin doesn’t deal with packages that are defined as downloadable or editable dependencies (i.e. the [tool.poetry.dependencies] section).


The plugin enables relative paths in the packages section, i.e. your code in Python namespace packages.


It looks like you have defined both “dependencies” and “packages” in your pyproject.toml for the same source code. Is there a reason for that?

**Comment by peeksake** [comment]
> The Multi-project plugin doesn’t deal with packages that are defined as downloadable or editable dependencies (i.e. the [tool.poetry.dependencies] section).
The plugin enables relative paths in the packages section, i.e. your code in Python namespace packages.

Ack, in this case I'll close the bug. By the off chance do you know how this might be solvable?
 
 > It looks like you have defined both “dependencies” and “packages” in your pyproject.toml for the same source code. Is there a reason for that?
 
 Just in an effort to rule out the possibility of the dependency section being able to traverse the tree and pull out the necessary dependencies of `core`.

**Comment by DavidVujic** [comment]
I’ll think about if it would be a good fit for this plug-in! I think there are other ones out there targeting local dependencies, but not sure how production ready they are.


In case you haven’t checked it out already, the Polylith architecture could be an alternative. I’m the developer of the tooling for it too (there’s a Poetry plug-in and a stand-alone CLI).
