### ISSUE TITLE
Configuring additional files to ignore when copying the project

### ISSUE THREAD

**Issue by bnmnetp** [DavidVujic/poetry-multiproject-plugin#62]
**Is your feature request related to a problem? Please describe.**
I have a couple of large folders that are needed for development, but not as part of building the wheel.  I would like to ignore those folders when the .prepare_xxx directory is created.  Copying these makes building the project noticeably slower.

**Describe the solution you'd like**
I see that you already have a place in copy_project where you are using `shutil.ignore_patterns`. But I would love it if there was a way to configure the pyproject.toml file with additional files/folders to ignore.

**Comment by DavidVujic** [comment]
Poetry has support for configuring files and folders to exclude when building wheels and sdists. Maybe this will solve the building part of it? https://python-poetry.org/docs/pyproject/#include-and-exclude

I'll make sure the `build-project` command will use the `exclude` section when copying the contents and will have a look at it right away. I'll write an update here in this issue when there is a new version of the multiproject plugin available.

My initial idea is to append the existing `shutil` exclude pattern with what's configured in the `tool.poetry.exclude` section, when using the defaults. If there is a `wheel` only exclude, the copying will still be done (to be able to build a proper `sdist`). 

What do you think about this approach?

**Comment by bnmnetp** [comment]
I think using the existing `exclude` mechanism would be perfect.

**Comment by DavidVujic** [comment]
@bnmnetp There's a new version out (v1.6.0) that will append any existing `exclude` patterns. 

This is using the Poetry featurea and is per-project: the `exclude` pattern should be added in the project-specific `pyproject.toml` files.

I hope this solves the issue and makes the builds faster!

**Comment by bnmnetp** [comment]
Thank you very much.   A huge difference in build time!
