### ISSUE TITLE
Add capability to build wheel using locked dependencies

### ISSUE THREAD

**Issue by davzucky** [DavidVujic/poetry-multiproject-plugin#64]
**Is your feature request related to a problem? **

Using this library, we are migrating from a multi-repository model to a polylith model. On the multi-repository model, we used this library to ensure we were generating wheel files using the lock dependencies: https://github.com/bneijt/poetry-lock-package/tree/main.
We want to enable that when building the project. 

**Describe the solution you'd like**
Add a flag ```--include-lock-dependencies``` that would pin the version

**Describe alternatives you've considered**
I manually run the poetry lock package through all the project folders.

**Comment by DavidVujic** [comment]
Have you been able to try out my suggestion @davzucky?

**Comment by davzucky** [comment]
@DavidVujic, thank you for getting back to me.

I moved away from Poetry and used the opportunity to migrate to UV. Using UV and your polylith tool, I could create what I wanted and build a clean Docker image.

I updated the docker file from your sample to allow you to build the environment using uv lock file. Compared to your sample, the new dockerfile brings.

- Multistage build 
- Build env using uv lock file
- Able to work on top of any base distro as it uses uv to brink the Python binary as well

``` Dockerfile
FROM ubuntu:noble-20240801 AS build

WORKDIR /code

COPY . .
ENV UV_PYTHON_INSTALL_DIR=/opt/python

COPY --from=ghcr.io/astral-sh/uv:0.4.0 /uv /bin/uv

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=SC1091
RUN python_version=$(grep -oP "(?<=requires-python = \").*(?=\")" pyproject.toml | sed 's/^==//g') && \
    uv venv --python "$python_version" --relocatable --link-mode copy && \
    uv sync --frozen --link-mode copy --no-dev --compile-bytecode --no-cache --no-install-project && \
    . ./.venv/bin/activate && \
    uv pip install --no-deps --compile-bytecode --no-cache ./dist/*.whl


# Build runtime docker image
FROM ubuntu:noble-20240801 AS runtime

COPY --from=build /code/.venv /opt/venv
COPY --from=build /opt/python /opt/python

ENV PATH="/opt/venv/bin:$PATH"

RUN groupadd --system fastapi && \
    useradd --system -g fastapi fastapi

USER fastapi

WORKDIR /app

```
