### ISSUE TITLE
Using editable installs with `hatch`

### ISSUE THREAD

**Issue by NellyWhads** [DavidVujic/poetry-multiproject-plugin#68]
**Describe the bug**
When I create `uv` `hatch`-backed project and install it, all modules within the regular package structure (ie. within the `project` directory) install as `editable`. However, all `bricks` do not install in `editable` mode. This requires me to constantly run `uv sync --reinstall-module {project-name}` along with any other dep groups to update the sources in the `.venv` and then re-start my python notebooks to pick up the change. This is rather annoying since the `%autoreload` decorators don't work properly, and I have to basically re-build the wheel on every change to a component. This was not the behavior when using the `poetry` plugin.

**To Reproduce**
1. Use a polylithic config as exemplified in this repo backed by `uv` and `hatch`
2. Install the project using `uv`'s default methods (ie. `uv sync {args}`)
3. Make a change to a `brick` (I currently only use `components`) like adding a new class
4. Attempt to access the new class from a script or an interactive `uv run python`/`uv run ipython` session
    4.1. Activate the `uv` `.venv` manually and try again
    4.2. Use a code editor like `VSCode` to trace the location of the module and find it to be in `.venv/lib/{python-version}/site-package/{namespace}/{module}` instead of the expected `{workspace}/components/{namespace}/{module}`
    4.3. Be sad
6. Update the sources using `uv sync --reinstall-module {project-name}`
7. Try step `4.` again, this time, skipping `4.3.`

**Error Log**
No logs available.

**Expected behavior**
I expect editable access to the `bricks` along with the `project`.

**Desktop (please complete the following information):**
 - OS: `MacOS Sonoma` `Ubuntu 20.04` `Ubuntu 22.04` `Ubuntu 24.04`
 - Python version: `3.8-3.11`
 - UV version: `0.5`

**Comment by DavidVujic** [comment]
I think this issue should be in the Polylith repo. I have reopened the previously closed one. Closing this one.
