### ISSUE TITLE
another similar plugin

### ISSUE THREAD

**Issue by bhelgs** [DavidVujic/poetry-multiproject-plugin#8]
Hello,

I saw your poetry-core PR to add workspaces. Thanks and I hope it works out!

As I was looking through available solutions I also found [this plugin](https://github.com/jacksmith15/poetry-workspace-plugin). 
I haven't had enought time yet to look in much detail but I thought you might be interested in seeing/comparing.

Anyway, thanks and have a good day!

**Comment by DavidVujic** [comment]
Hi @bhelgs! I have looked into that repo before, and I have learned a lot about how to develop a Poetry plugin in general from the source code there. I think it has a different view on workspaces than the PR I currently have at the Poetry-core repo, but looks promising! Thank you for sharing!

**Comment by bhelgs** [comment]
good to hear. thanks for all that you have done!

**Comment by bhelgs** [comment]
Hi again, 

Would it make sense to use the concept of workspaces to maintain/lock an "operational environment"?

I guess I am thinking about users that do not use something like Docker to isolate each of their components.

**Comment by DavidVujic** [comment]
That's an interesting idea! 

I haven't thought about it in that way, I usually see a workspace as the possibility to have several projects in one (mono)repo, and making it possible to share code between the projects during the development. A build process would create separate artifacts that would run in isolation (in Docker, or maybe in a virtual environment).
